@startuml
'https://plantuml.com/class-diagram

interface GradeEvaluation
class BasicEvaluation
class MajorEvaluation
class PassFailEvaluation

GradeEvaluation <-- BasicEvaluation
GradeEvaluation <-- MajorEvaluation
GradeEvaluation <-- PassFailEvaluation

@enduml